### PR TITLE
fixed plugin install instructions

### PR DESCRIPTION
**Pull request by ghost**
Plug Install instructions states inspired-github for the repo name while it should state inspired-github.vim

### CODE REVIEW

**Comment by mvpopuk** [comment]
Have you tried installing it without the .vim extension ?

**Comment by ghost** [comment]
Yes.
using the current README, I get the following error:
```
 inspired-github:                                                                                                       
    Cloning into '/home/egoist/.vim/plugged/inspired-github'...                                                        
    fatal: could not read Username for 'https://github.com': terminal prompts disabled  
```
I am assuming that's because vim-plug uses the github repo, which is why it's refusing to clone a repo that it can't find.

**Comment by mvpopuk** [comment]
That's strange because I installed it without any issues using `vim-plug` and following the instructions I wrote in the readme. Have you tried using the `.vim` extension and it worked ?

**Comment by mvpopuk** [comment]
I got the [same PR](https://github.com/mvpopuk/inspired-github.vim/pull/1) from @khalidchawtany but without any explanations what is the PR actually fixing.

**Comment by pmrt** [comment]
Same error for me (Neovim nightly with packer). I managed to install it by adding .vim without any issues. I guess this is because the package manager.

Anyway, the safer way is always the full path for the name as the PR suggests. Examples:
- nvim-telescope/telescope.nvim
- kyazdani42/nvim-tree.lua
- jose-elias-alvarez/null-ls.nvim

**Comment by ghost** [comment]
> That's strange because I installed it without any issues using `vim-plug` and following the instructions I wrote in the readme. Have you tried using the `.vim` extension and it worked ?

I can confirm that using the `.vim` extension fixes the issue

**Comment by mvpopuk** [comment]
Merged. Thanks @xEgoist

**Pull request merged**
